### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by szzz666** [lt-name/MurderMystery_Nukkit#107]
Nukkit PM1E 1.19.80.2964服务端
MurderMystery v1.4.2-PM1E-SNAPSHOT
是在你的构建站下载的1.4.2版本

Could not pass event 'cn.nukkit.event.player.PlayerCommandPreprocessEvent' to 'MurderMystery v1.4.2-PM1E-SNAPSHOT': null on cn.lanink.murdermystery.listener.defaults.DefaultChatListener
2023-06-03 13:58:31.739 [Nukkit] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:18) ~[patched.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:18) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:135) ~[patched.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:3589) ~[patched.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:3) ~[patched.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:69) ~[patched.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:173) ~[patched.jar:?]
	at cn.nukkit.Server.f(Server.java:589) ~[patched.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1229) ~[patched.jar:?]
	at cn.nukkit.Server.start(Server.java:311) ~[patched.jar:?]
	at cn.nukkit.Server.<init>(Server.java:521) ~[patched.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:12) ~[patched.jar:?]
	at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at cn.lanink.murdermystery.listener.defaults.DefaultChatListener.onCommandPreprocess(DefaultChatListener.java:32) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:15) ~[patched.jar:?]
	... 13 more

**Comment by lt-name** [comment]
已修复，请更新到最新快照测试
