### ISSUE TITLE
bug..?

### ISSUE THREAD

**Issue by mcsim415** [lt-name/MurderMystery_Nukkit#14]
When 2 players join a game,
then this message logged.

21:41:22[WARN ] Received packet violation warning: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=FINAL_WARNING, packetId=108, context=)

And two players leave the game on itself.
Two players didn't touch leave button!

**Comment by lt-name** [comment]
I have not encountered this problem, are you using the master branch of nk

**Comment by mcsim415** [comment]
Yes. [feature/1.16](https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/feature%252F1.16/). I use thisbranch.

**Comment by lt-name** [comment]
Maybe nk's problem
I used only one sound package, and the rest was handled by nk itself

**Comment by mcsim415** [comment]
How I solve this problem?

**Comment by lt-name** [comment]
I did not reproduce the problem, can you record a video?

**Comment by mcsim415** [comment]
You might not understand because you have Korean, is that okay?

**Comment by lt-name** [comment]
If possible, try to use Chinese

**Comment by mcsim415** [comment]
Ok. got it.

**Comment by mcsim415** [comment]
How I upload video?

**Comment by lt-name** [comment]
You can use a network drive, such as OneDrive
It is best to download without logging in

**Comment by mcsim415** [comment]
[here?](https://vimeo.com/user118844189/review/434934902/d7fa6df8ca)

**Comment by mcsim415** [comment]
Skip it from time to time.

**Comment by mcsim415** [comment]
Did you watch it?

**Comment by lt-name** [comment]
The page does not exist...

**Comment by mcsim415** [comment]
Sorry, I'll upload video at google drive next time

**Comment by lt-name** [comment]
Can you send a complete error report？

**Comment by lt-name** [comment]
The version I tested is Nukkit git-647b8cd does not have this problem

**Comment by mcsim415** [comment]
I think it's my server's fault.

**Comment by mcsim415** [comment]
I'll send you all my server files.

**Comment by mcsim415** [comment]
Can you test?

**Comment by lt-name** [comment]
Maybe you can try to update nk and then uninstall all plugins to test
If there is no problem, install the plug-ins one by one to test

**Comment by mcsim415** [comment]
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
        at cn.nukkit.level.generator.Flat.parsePreset(Flat.java:145)
        at cn.nukkit.level.generator.Flat.generateChunk(Flat.java:160)
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:104)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:49)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:54)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:44)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.valueOf(Integer.java:983)
        at cn.nukkit.level.generator.Flat.parsePreset(Flat.java:92)
        ... 17 more

**Comment by mcsim415** [comment]
It is Runtime error.

**Comment by mcsim415** [comment]
Maybe it is nukkit's fault.

**Comment by lt-name** [comment]
Are you using java 8 ？

**Comment by mcsim415** [comment]
openjdk version "11.0.7" 2020-04-14

**Comment by mcsim415** [comment]
root@webhost:~/testn# java -version
openjdk version "11.0.7" 2020-04-14

**Comment by lt-name** [comment]
nk is developed based on java8, please use java8

**Comment by mcsim415** [comment]
ok

**Comment by lt-name** [comment]
If it is not resolved, you can try to replace the map, this error is related to the map

**Comment by mcsim415** [comment]
Thx!

**Comment by lt-name** [comment]
This issue has nothing to do with murdermystery, so I will delete this issue
