### ISSUE TITLE
MurderMystery - Tip Error?

### ISSUE THREAD

**Issue by JuChanMin** [lt-name/MurderMystery_Nukkit#24]
I using BlockHunt, HotPotato, MurderMystery, LobbyNK, PlaceholderAPI, Tips.

and When I use '/hotpotato join' ..
(PetteriM1 Edition)

> 2020-08-11 23:56:42.726 [Nukkit Asynchronous Task Handler #7] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.ScoreBoardTask$1.onRun(ScoreBoardTask.java:67) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[Nukkit-PM1E.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-11 23:56:42.704 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[Nukkit-PM1E.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: name.murdermystery.api.Api
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[Nukkit-PM1E.jar:?]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[Nukkit-PM1E.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 7 more
2020-08-11 23:56:42.845 [Thread-24] INFO  - [BugReport] Sending a bug report ...
2020-08-11 23:56:42.937 [Thread-25] INFO  - [BugReport] Sending a bug report ...
2020-08-11 23:56:43.687 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[Nukkit-PM1E.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-11 23:56:43.719 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.ScoreBoardTask$1.onRun(ScoreBoardTask.java:67) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[Nukkit-PM1E.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-11 23:56:43.737 [Thread-27] INFO  - [BugReport] Sending a bug report ...
2020-08-11 23:56:43.745 [Thread-29] INFO  - [BugReport] Sending a bug report ...
2020-08-11 23:56:44.685 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[Nukkit-PM1E.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-11 23:56:44.685 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.ScoreBoardTask$1.onRun(ScoreBoardTask.java:67) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[Nukkit-PM1E.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-11 23:56:44.694 [Thread-32] INFO  - [BugReport] Sending a bug report ...
2020-08-11 23:56:44.702 [Thread-33] INFO  - [BugReport] Sending a bug report ...

(infinity ERROR)
When I leave game, Error was stopped.

When I use '/hotpotato join' in NukkitX..

> 2020-08-12 00:53:13.621 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: name.murdermystery.api.Api
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 7 more
2020-08-12 00:53:13.639 [Thread-23] INFO  - [BugReport] 오류가 감지되었습니다, 버그 보고서를 생성합니다.
2020-08-12 00:53:13.648 [Thread-23] INFO  - [BugReport] 버그 보고서가 생성되었습니다: C:\Users\J\Desktop\새 폴더\logs\bug_reports\20200812005313_NoClassDefFoundError.md
2020-08-12 00:53:14.619 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-12 00:53:14.632 [Thread-25] INFO  - [BugReport] 오류가 감지되었습니다, 버그 보고서를 생성합니다.
2020-08-12 00:53:14.635 [Thread-25] INFO  - [BugReport] 버그 보고서가 생성되었습니다: C:\Users\J\Desktop\새 폴더\logs\bug_reports\20200812005314_NoClassDefFoundError.md
2020-08-12 00:53:15.620 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-12 00:53:15.629 [Thread-27] INFO  - [BugReport] 오류가 감지되었습니다, 버그 보고서를 생성합니다.
2020-08-12 00:53:15.635 [Thread-27] INFO  - [BugReport] 버그 보고서가 생성되었습니다: C:\Users\J\Desktop\새 폴더\logs\bug_reports\20200812005315_NoClassDefFoundError.md
2020-08-12 00:53:16.619 [Nukkit Asynchronous Task Handler #8] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: name/murdermystery/api/Api
	at tip.utils.Api.getB(Api.java:176) ~[?:?]
	at tip.utils.Api.strReplace(Api.java:378) ~[?:?]
	at tip.tasks.TipTask$1.onRun(TipTask.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-08-12 00:53:16.628 [Thread-29] INFO  - [BugReport] 오류가 감지되었습니다, 버그 보고서를 생성합니다.
2020-08-12 00:53:16.633 [Thread-29] INFO  - [BugReport] 버그 보고서가 생성되었습니다: C:\Users\J\Desktop\새 폴더\logs\bug_reports\20200812005316_NoClassDefFoundError.md

(infinity ERROR too.. XD)
When I leave game, Error was stopped.

Its my problem?

Even if I delete the configuration file of the TIP, an error is printed :c

and.. My English is terrible, Sorry Xdd ..

**Comment by lt-name** [comment]
Tips version is too low

**Comment by JuChanMin** [comment]
oooh Thank you XD
I used 1.7.8 and fixed this bug :D
