### ISSUE TITLE
加载房间时没有判断随机出生点数量

### ISSUE THREAD

**Issue by VadimB131** [lt-name/MurderMystery_Nukkit#7]
Hi!

Installed plugin but when the game starts I get an error:

 Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[minecraft.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[minecraft.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [minecraft.jar:?]
        at cn.lanink.murdermystery.tasks.WaitTask.onRun(WaitTask.java:55) [MurderMystery-1.0.3-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.Task.run(Task.java:51) [minecraft.jar:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [minecraft.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [minecraft.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [minecraft.jar:?]
        at cn.nukkit.Server.tick(Server.java:1140) [minecraft.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [minecraft.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [minecraft.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [minecraft.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [minecraft.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_252]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_252]
        at cn.lanink.murdermystery.listener.MurderListener.onRoomStart(MurderListener.java:59) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[minecraft.jar:?]
        ... 12 more

**Comment by lt-name** [comment]
Please use /kadmin addrandomspawn to add a random birth point

**Comment by lt-name** [comment]
Fixed room configuration check
You can download the latest version from github actions
https://github.com/lt-name/MurderMystery_Nukkit/actions
(Google Translate)

**Comment by VadimB131** [comment]
thanks!
